# Generated by Django 2.0.12 on 2020-04-29 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('ItselfIntro', models.TextField(max_length=120)),
                ('AdventureIntro', models.TextField(max_length=120)),
                ('SkillsIntro', models.TextField(max_length=120)),
                ('JobIntro', models.TextField(max_length=120)),
                ('SchollingIntro', models.TextField(max_length=360)),
                ('ContactIntro', models.TextField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
